management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      validate-group-membership: false
      show-details: never
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,dependencyReadiness
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        credit.evaluation.duration: true
      slo:
        http.server.requests: 100ms,250ms,500ms,1s
        credit.evaluation.duration: 100ms,250ms,500ms,1s
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:0.1}
    export:
      otlp:
        enabled: ${OTEL_TRACING_ENABLED:false}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
  otlp:
    metrics:
      export:
        enabled: ${OTEL_METRICS_ENABLED:false}
        url: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT:http://localhost:4318/v1/metrics}

logging:
  structured:
    format:
      console: logstash
    json:
      exclude:
        - cpf
        - token
        - amount
        - requestBody
        - payload
      add:
        service.name: ${spring.application.name}
        service.version: ${APP_VERSION:unknown}
        service.environment: ${APP_ENVIRONMENT:local}
