management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      validate-group-membership: false
      show-details: never
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,dependencyReadiness
  metrics:
    tags:
      application: ${spring.application.name}
