management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      validate-group-membership: false
      show-details: never
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,dependencyReadiness
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  structured:
    format:
      console: logstash
    json:
      exclude:
        - cpf
        - token
        - amount
        - requestBody
        - payload
      add:
        service.name: ${spring.application.name}
        service.version: ${APP_VERSION:unknown}
        service.environment: ${APP_ENVIRONMENT:local}
